#!/usr/bin/env bash
set -euo pipefail

preset="${1:?preset required: minimal or full}"

write_if_set() {
  if [[ -n "${2:-}" ]]; then
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}

: > .env

write_if_set POCKETBASE_URL "${POCKETBASE_URL:-}"
write_if_set POCKETBASE_TOKEN "${POCKETBASE_TOKEN:-}"
write_if_set VITE_FIRECRAWL_BASE_URL "${VITE_FIRECRAWL_BASE_URL:-}"
write_if_set VITE_FIRECRAWL_API_KEY "${VITE_FIRECRAWL_API_KEY:-}"
write_if_set VITE_PROXY_URL "${VITE_PROXY_URL:-}"
write_if_set VITE_PROXY_TOKEN "${VITE_PROXY_TOKEN:-}"
write_if_set VITE_COMPARATASAS_DEPLOY_HOOK_URL "${VITE_COMPARATASAS_DEPLOY_HOOK_URL:-}"

if [[ "$preset" != "full" ]]; then
  exit 0
fi

write_if_set VITE_AXIOM_ORG_ID "${VITE_AXIOM_ORG_ID:-}"
write_if_set VITE_AXIOM_TOKEN "${VITE_AXIOM_TOKEN:-}"
write_if_set VITE_AXIOM_DATASET "${VITE_AXIOM_DATASET:-}"
write_if_set VITE_BANXICO_TOKEN "${VITE_BANXICO_TOKEN:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_NEXO_URL "${VITE_FINANZAS_RENDIMIENTOS_NEXO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_NEXO_API_KEY "${VITE_FINANZAS_RENDIMIENTOS_NEXO_API_KEY:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_FIWIND_URL "${VITE_FINANZAS_RENDIMIENTOS_FIWIND_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_LETSBIT_URL "${VITE_FINANZAS_RENDIMIENTOS_LETSBIT_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_BELO_URL "${VITE_FINANZAS_RENDIMIENTOS_BELO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_LEMONCASH_URL "${VITE_FINANZAS_RENDIMIENTOS_LEMONCASH_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_RIPIO_URL "${VITE_FINANZAS_RENDIMIENTOS_RIPIO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_SATOSHITANGO_URL "${VITE_FINANZAS_RENDIMIENTOS_SATOSHITANGO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_LUCAMONEY_URL "${VITE_FINANZAS_RENDIMIENTOS_LUCAMONEY_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_LUNEFI_URL "${VITE_FINANZAS_RENDIMIENTOS_LUNEFI_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_DECRYPTO_URL "${VITE_FINANZAS_RENDIMIENTOS_DECRYPTO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_VESSEO_URL "${VITE_FINANZAS_RENDIMIENTOS_VESSEO_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_BERRY_URL "${VITE_FINANZAS_RENDIMIENTOS_BERRY_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_BERRY_TOKEN "${VITE_FINANZAS_RENDIMIENTOS_BERRY_TOKEN:-}"
write_if_set VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_URL "${VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_URL:-}"
write_if_set VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_CLIENT_ID "${VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_CLIENT_ID:-}"
write_if_set VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_CLIENT_SECRET "${VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_CLIENT_SECRET:-}"
write_if_set VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_AUDIENCE "${VITE_FINANZAS_PLAZOFIJO_NARANJAX_TOKEN_AUDIENCE:-}"
write_if_set VITE_FINANZAS_PLAZOFIJO_NARANJAX_URL "${VITE_FINANZAS_PLAZOFIJO_NARANJAX_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_UALA_TOKEN_URL "${VITE_FINANZAS_RENDIMIENTOS_UALA_TOKEN_URL:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_UALA_USERNAME "${VITE_FINANZAS_RENDIMIENTOS_UALA_USERNAME:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_UALA_PASSWORD "${VITE_FINANZAS_RENDIMIENTOS_UALA_PASSWORD:-}"
write_if_set VITE_FINANZAS_RENDIMIENTOS_UALA_URL "${VITE_FINANZAS_RENDIMIENTOS_UALA_URL:-}"
write_if_set VITE_CARREFOUR_API_URL "${VITE_CARREFOUR_API_URL:-}"
write_if_set VITE_GLOBAL66_API_URL "${VITE_GLOBAL66_API_URL:-}"
write_if_set VITE_GLOBAL66_API_KEY "${VITE_GLOBAL66_API_KEY:-}"
write_if_set VITE_FINANZAS_CRESIUM_URL "${VITE_FINANZAS_CRESIUM_URL:-}"
write_if_set VITE_FINANZAS_BELO_CUENTA_REMUNERADA_URL "${VITE_FINANZAS_BELO_CUENTA_REMUNERADA_URL:-}"
write_if_set VITE_FINANZAS_CAPYFI_API_URL "${VITE_FINANZAS_CAPYFI_API_URL:-}"
write_if_set VITE_FINANZAS_CAPYFI_TOKEN "${VITE_FINANZAS_CAPYFI_TOKEN:-}"
write_if_set VITE_FINANZAS_CAPYFI_CHAIN_ID "${VITE_FINANZAS_CAPYFI_CHAIN_ID:-}"
write_if_set VITE_FINANZAS_CAPYFI_CTOKEN_ADDRESS "${VITE_FINANZAS_CAPYFI_CTOKEN_ADDRESS:-}"
write_if_set VITE_GSHEETS_API_KEY "${VITE_GSHEETS_API_KEY:-}"
write_if_set VITE_GSHEETS_ASTROPAY_SPREADSHEET_ID "${VITE_GSHEETS_ASTROPAY_SPREADSHEET_ID:-}"
write_if_set VITE_GSHEETS_LETRAS_SPREADSHEET_ID "${VITE_GSHEETS_LETRAS_SPREADSHEET_ID:-}"
write_if_set VITE_OPENROUTER_KEY "${VITE_OPENROUTER_KEY:-}"
write_if_set VITE_TABSTACK_API_KEY "${VITE_TABSTACK_API_KEY:-}"
