import {
  PRIVATE_RULES,
  dateField,
  numberField,
  textField,
} from './fields.js'

export const REM_EXPECTATIVAS_COLLECTION = {
  name: 'rem_expectativas',
  type: 'base',
  ...PRIVATE_RULES,
  fields: [
    textField('informe', { required: true }),
    textField('fecha'),
    textField('muestra', { required: true }),
    textField('indicador', { required: true }),
    textField('periodo', { required: true }),
    textField('periodoTipo'),
    textField('periodoDesde'),
    textField('periodoHasta'),
    textField('referencia', { required: true }),
    textField('referenciaFecha'),
    textField('unidad'),
    numberField('mediana'),
    numberField('promedio'),
    numberField('desvio'),
    numberField('maximo'),
    numberField('minimo'),
    numberField('percentil90'),
    numberField('percentil75'),
    numberField('percentil25'),
    numberField('percentil10'),
    numberField('participantes', { onlyInt: true }),
    textField('fuente'),
    textField('publicacionUrl'),
    textField('xlsxUrl'),
    dateField('fechaActualizacion', { required: true }),
  ],
  indexes: [
    'CREATE UNIQUE INDEX idx_rem_expectativas_pk ON rem_expectativas (informe, muestra, indicador, periodo, referencia)',
    'CREATE INDEX idx_rem_expectativas_informe ON rem_expectativas (informe)',
    'CREATE INDEX idx_rem_expectativas_indicador ON rem_expectativas (indicador)',
  ],
}
